# Generated by Django 4.1.13 on 2024-04-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_address', models.CharField(max_length=500)),
                ('geocoded_address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geotag_provider', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fortepan_id', models.IntegerField()),
                ('description_original', models.TextField()),
                ('description_geocoded', models.TextField()),
            ],
            options={
                'db_table': 'photos',
            },
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['fortepan_id'], name='photos_fortepa_481ebe_idx'),
        ),
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='photos.photo'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude'], name='locations_latitud_e25f00_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['longitude'], name='locations_longitu_56be5a_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['geotag_provider'], name='locations_geotag__298b6b_idx'),
        ),
    ]
