# Generated by Django 4.1.13 on 2024-05-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='place',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
