# Generated by Django 4.1.13 on 2024-06-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
