# Generated by Django 4.1.13 on 2024-08-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('ELL_VAR', 'Ellenőrzésre vár'), ('ELH_VAR', 'Elhelyezésre vár'), ('OK', 'Elhelyezve'), ('NK', 'Nincs Koordináta')], db_index=True, default='ELL_VAR', max_length=8),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['place'], name='photos_place_4e88ac_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['status'], name='photos_status_db27ce_idx'),
        ),
    ]
