# Generated by Django 4.1.13 on 2024-09-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_location_date_created_location_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='editor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['editor'], name='photos_editor_e6fbaf_idx'),
        ),
    ]
