# Generated by Django 4.1.13 on 2024-09-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_photo_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='shooting_location',
            field=models.BooleanField(default=False),
        ),
    ]
