# Generated by Django 4.1.13 on 2024-11-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_location_shooting_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['fortepan_id']},
        ),
    ]
